name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      env:
        FOO_BAR_SECRET: ${{ secrets.FOO_BAR_SECRET }}
      run: |
        echo $FOO_BAR_SECRET
        echo $FOO_BAR_SECRET | tr 'A-Za-z' 'N-ZA-Mn-za-m'
